=== ehn-dcc-development/dcc-business-rules-generator/src/resources/specification.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://id.uvci.eu/dcc-rules-generator/specification.schema.json",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "country": {
      "type": "string",
      "description": "ISO 3166-1 alpha-2 country code",
      "pattern": "^[A-Z]{2}$"
    },
    "validFrom": {
      "type": "string",
      "description": "start validity of the rules to generate, as ISO 8601 timestamp (without ms, with timezone)",
      "format": "date-time",
      "pattern": "^\\d{4}-[01]\\d-[0-3]\\dT[0-2]\\d:[0-5]\\d:[0-5]\\d([-+][0-2]\\d:[0-5]\\d|Z)$"
    },
    "vaccineSpecs": {
      "type": "array",
      "items": {
        "$ref": "#/$defs/VaccinesSpecification"
      },
      "minItems": 1
    },
    "maxValid": {
      "type": "integer",
      "minimum": 1
    }
  },
  "required": [
    "country",
    "validFrom",
    "vaccineSpecs"
  ],
  "$defs": {
    "RecognisedVaccines": {
      "type": "string",
      "enum": [
        "Abdala",
        "BBIBP-CorV",
        "CVnCoV",
        "Convidecia",
        "CoronaVac",
        "Covaxin",
        "CoviVac",
        "Covid-19-recombinant",
        "Covishield",
        "EU/1/20/1507",
        "EU/1/20/1525",
        "EU/1/20/1528",
        "EU/1/21/1529",
        "EU/1/21/1618",
        "EpiVacCorona",
        "Hayat-Vax",
        "Inactivated-SARS-CoV-2-Vero-Cell",
        "MVC-COV1901",
        "NVX-CoV2373",
        "R-COVI",
        "Sputnik-Light",
        "Sputnik-V",
        "WIBP-CorV"
      ]
    },
    "VaccinesSpecification": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "vaccineIds": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/RecognisedVaccines"
          },
          "minItems": 1
        },
        "comboSpecs": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/ComboSpecification"
          },
          "minItems": 1
        }
      },
      "required": [
        "vaccineIds",
        "comboSpecs"
      ]
    },
    "ComboSpecification": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "combos": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/Combo"
          },
          "minItems": 1
        },
        "validity": {
          "$ref": "#/$defs/Validity"
        }
      },
      "required": [
        "combos",
        "validity"
      ]
    },
    "Combo": {
      "type": "string",
      "enum": [
        "1/1",
        "2/2",
        "2/1",
        "3/3",
        "3/2",
        "3/1",
        "n/n, n > 3",
        "n/1, n > 3",
        "other"
      ]
    },
    "Validity": {
      "oneOf": [
        {
          "type": "null"
        },
        {
          "type": "integer",
          "minimum": 0
        },
        {
          "$ref": "#/$defs/Range"
        }
      ]
    },
    "Range": {
      "type": "array",
      "items": {
        "type": "integer",
        "minimum": 0
      },
      "minItems": 1,
      "maxItems": 2
    }
  }
}

=== ehn-dcc-development/dcc-business-rules-generator/src/test/specs/test-spec.json
{
  "country": "NL",
  "validFrom": "2021-12-05T00:00:00+01:00",
  "vaccineSpecs": [
    {
      "vaccineIds": [ "EU/1/20/1528" ],
      "comboSpecs": [
        {
          "combos": [ "1/1" ],
          "validity": null
        },
        {
          "combos": [ "2/2" ],
          "validity": 14
        },
        {
          "combos": [ "3/3", "3/2", "n/n, n > 3" ],
          "validity": 0
        }
        ]
    },
    {
      "vaccineIds": [ "EU/1/20/1525" ],
      "comboSpecs": [
        {
          "combos": [ "1/1" ],
          "validity": 28
        },
        {
          "combos": [ "2/2", "3/3", "n/n, n > 3" ],
          "validity": 0
        },
        {
          "combos": [ "3/2" ],
          "validity": null
        }
      ]
    }
  ],
  "maxValid": 365
}
